### ISSUE TITLE
Closed Caption

### ISSUE THREAD

**Issue by rctvhd** [rokudev/hero-grid-channel#1]
Hello! thanks for this great Xample.
I need option or learn how to add closed caption or subtitles to this chhanel.

Please! Help.

Thanks

**Comment by LeoWW** [comment]
Hey rctvhd: 
To add subtitles to a video, you need to set the subtitleConfig field of the Video node's contentNode like so:
`ContentNode.subtitleConfig = {Trackname: "pkg:/source/CraigVenter.srt" }`

The trackname in this example is a local `.srt` file. An implementation of adding subtitles can be seen in my simple videoplayer channel repo: https://github.com/rokudev/simple-videoplayer-channel

The local .srt file is located here to give you a sense of how they look like:
https://github.com/rokudev/simple-videoplayer-channel/blob/master/source/CraigVenter.srt

If your subtitle files are hosted along with your content, you will need to parse them in `Parser.brs` and add them to the Video's contentNode.
